### ISSUE TITLE
on my.protospace.ca 'home' - displays only one member card number

### ISSUE THREAD

**Issue by frollard** [Protospace/spaceport#10]
https://github.com/Protospace/spaceport/blob/ba5361f660abcda087e6bde1fdbb4e0a8a33dba1/webclient/src/Home.js#L94

Currently is (legacy) possible to have multiple cards assigned to one user. 
/cards shows correct card assignments.
Home only shows the most recent used card assigned to the user. Perhaps making the card number a list, or hyperlinking the card number value to /cards would be appropriate.

**Comment by tannercollin** [comment]
Fixed in bc067f5d6dec6a6fc22f72b1978e9a4ff5a77a98, refresh to see the change. Thanks Jamie!
