### ISSUE TITLE
Allow instructors to fail students

### ISSUE THREAD

**Issue by VE6AFT** [Protospace/spaceport#114]
There are occasions when a trainer cannot in good/responsible conscience sign off a student as qualified on a tool, and a way to track these occurrences within the existing training/certification system would be useful. Typically this would be solved by marking the student as Withdrawn or some other status, but that doesn't accurately reflect the reasoning nor allow for instructors to follow-up and offer retraining opportunities.

As shown below, is it feasible to add a "Failed" button, and track that status like any other certification result?

Might members be offended by "failing"? Maybe "Attempted" instead  - but that looks a lot like "Attended" - so should that be "Passed"?

Should/could the Failed status be hidden from the public training records, visible only to trainers?

![image](https://user-images.githubusercontent.com/27093911/221396689-5abd6e84-6968-48ea-afb8-5152d647fcf3.png)

**Comment by tannercollin** [comment]
Has this happened before? Is there someone you'd mark that way if the feature was added?

**Comment by VE6AFT** [comment]
I have refused one Trotec practical and "withdrew" the cert for a member who refused to follow direction, proving unable to perform the basic tasks required to safely operate the tool.

Woodshop instructors express safety concerns about members who lack the manual skills or good judgement to be certified on our flesh-ripping tools, resulting in a recent rise in injuries.

"we had a guy who took the new members orientation, came to get vetted and couldn’t answer any of the basic 7 safety questions (where are the fire exits, fire extinguishers, first aid kit, eyewash station, muster point, address for the space and safety equipment cabinet.) He was within line of sight of 4 of them and couldn’t come up with any. He ended up leaving and didn’t get vetted."

"(redacted) rarely actually stays through a whole class and just sorta pops in now and then for a minute. Others show up late or leave half way and then just expect to pass pretty commonly"

The idea is this provides a nonconfrontational way for trainers, of whom we already ask a lot, to officially un-stamp their approval of a student. I thought about adding a "notes" feature to this, but that seemed 
too [Zawinski](https://en.wikipedia.org/wiki/Jamie_Zawinski#Zawinski's_Law) and the instructor's name would probably suffice.

Trainers have also discussed incorporating basic, multiple choice "knowledge verification" quizzes at the end of their sessions; like some online quiz generator, accessible from the student's device, where we can actually/easily/automatically/technologically/non-biased-ly verify that this public stranger person was awake and has two braincells to rub together before unleashing them upon the Armripper9000.
