### ISSUE TITLE
feature request: query current schedule when adding a class

### ISSUE THREAD

**Issue by frollard** [Protospace/spaceport#12]
Would be super handy to have a little iframe/etc to show the current schedule of training to prevent collisions booking new classes.
Similar to how the previous instances of the current course are shown, it would be nice to see upcoming events to make sure the classroom is available.
eg.
https://my.protospace.ca/courses/321
![image](https://user-images.githubusercontent.com/1535306/76698000-6295c780-6663-11ea-82ce-1cdbcad767a6.png)

**Comment by tannercollin** [comment]
Good idea, added in 5da382ee355a95b154859768e4447af6540f55e0. Thanks!

![Screenshot from 2020-03-15 22-59-38](https://user-images.githubusercontent.com/6752449/76724478-af83a780-6710-11ea-8ace-cd14623715e4.png)
