### ISSUE TITLE
Paymaster, Send Protocoin, overlapping wrap on long member names #ux

### ISSUE THREAD

**Issue by VE6AFT** [Protospace/spaceport#125]
Chrome, desktop, Windows 10

https://my.protospace.ca/paymaster
Send Protocoin
Type or scroll to a long member name:
(How long? Is it longer/shorter on mobile?)

![image](https://github.com/Protospace/spaceport/assets/27093911/2cd56c22-a1aa-49a7-a02b-4f2c4bf88650)

**Comment by tannercollin** [comment]
Thanks should be fixed in [3f16fc8](https://github.com/Protospace/spaceport/commit/3f16fc8847d9479811d3048894bfa73237d63689).
