### ISSUE TITLE
Charts, in dark mode Locked/Opened is black on black

### ISSUE THREAD

**Issue by VE6AFT** [Protospace/spaceport#132]
https://my.protospace.ca/charts

![image](https://github.com/Protospace/spaceport/assets/27093911/044cb5ab-605b-4d1e-b29c-bf139008798e)

vs

![image](https://github.com/Protospace/spaceport/assets/27093911/1a8adac6-ba75-4a7c-b634-f21ca042b79a)

**Comment by tannercollin** [comment]
Thanks for the bug report! Fixed in 4d1e7860b614fff4c2054526e5c41c268d2f467f.
