### ISSUE TITLE
Feature request: Member list: search to include more fields

### ISSUE THREAD

**Issue by frollard** [Protospace/spaceport#15]
Perhaps only for the staff/admin permission level for privacy, to be able to search for members by email, or other database fields (like email, phone, address, emergency contact ++ et al). Haven't looked deep into the code to know, but I believe it only searches by name fields.

Alternately, or both: including email address to the search results could help sanity check on the fly. Right now shows name, joined, status. perhaps full email if admin level, and obfuscated abºººººcd@efgººººº.cººººº if non-admin/staff.

This would allow for easier maintenance of the forum membership where applications often only show up by email.

**Comment by tannercollin** [comment]
Added search by email in a3db260e08174c463c83dc6368df4d24319cbfa3.

It's a good idea, I could have used this last night trying to figure out who Jai was. I'll have to think about privacy before showing email in search results as it's an API change. For now you can just click the top result and check.

**Comment by frollard** [comment]
I was in exactly the same boat trying to figure out exactly the same email.
