### ISSUE TITLE
Transactions... Print Receipt shows a solid black page when Print Background / Background Graphics is enabled

### ISSUE THREAD

**Issue by VE6AFT** [Protospace/spaceport#75]
**OS:** Microsoft Windows 10 Enterprise N LTSC 64-bit version 1809 build 17763.2452
**Browser:** Waterfox G4.0.5.1 (64-bit)
and Brave Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

- Login to my.protospace.ca
- Navigate to Member... Transactions
- Click on any transaction date to load the transaction details
- Scroll down and choose the Print Receipt button
- In the browser's print dialog, enable the checkbox to "Print backgrounds" (Mozilla) or "Background Graphics" (Chromium, under the "More Settings" expand down arrow)
- (this setting may be enabled by default from previous print jobs)

**Expected behavior:** the receipt would preview and print as expected
**Actual result:** preview of a completely black page is shown; did not brave the ink cartridge to attempt, however opening the PDF in Adobe Acrobat shows that the contents are there, just behind a full-page black box.
**Workaround:** Disable option to print background graphics, however this may not be an obvious solution for all users, and the option is slightly hidden on Chrome/ium.

Choosing Dark/Light mode via the "moon" button in the lower right corner of Spaceport and clean reloading does not impact this behavior.

![image](https://user-images.githubusercontent.com/27093911/152289533-cfaa557b-e469-4a14-9e69-98d893076e2c.png)

![image](https://user-images.githubusercontent.com/27093911/152290922-91f90572-317d-430e-a4be-8e1ef94b64da.png)

**Comment by tannercollin** [comment]
Fixed in dbe57cffb2caa9c781f65216e063032ee5c33909. 10/10 bug report, thanks for it!
