### ISSUE TITLE
Editing date/time in field while booking new class throws error

### ISSUE THREAD

**Issue by VE6AFT** [Protospace/spaceport#83]
Tested in Chrome on mobile and desktop

Login to my.protospace.ca as a Trainer
Space... Classes...
Choose a class from the list
Under Instructor Panel, Add a Class
Put cursor into the Time and Date field
Press any key
(except for backspacing "PM" - try space, or anything else)

![image](https://user-images.githubusercontent.com/27093911/158258877-48083a3a-d268-4e47-afd6-75501cb54fa6.png)

Actual Result:

![image](https://user-images.githubusercontent.com/27093911/158258728-9a8f6cee-7996-4eb2-9630-f36011eb632b.png)

Expected: 

Not this; ideally, I'd be able to edit the date/time directly, but forcing datepicker only is fine too.

**Comment by tannercollin** [comment]
Wow, good catch! Fixed in 093ce1747c70a49e852baac4a871647b93cee92d.
