### ISSUE TITLE
Paymaster transactions for "Snacks, Pop, Coffee" come thru PayPal as "donation"

### ISSUE THREAD

**Issue by VE6AFT** [Protospace/spaceport#84]
![image](https://user-images.githubusercontent.com/27093911/161445380-889bd22e-ad16-4f89-be95-7100434bb4b8.png)

> All Paypal says is "Protospace: donation". I will record it as soda/snacks.

For financial tracking reasons, these should some thru PayPal with a transaction note specifying that they're for snacks/pop/coffee.

**Comment by tannercollin** [comment]
Good catch! Fixed in ee60ec643ae9e4694d35968c77de18ab37ee1914.

**Comment by VE6AFT** [comment]
Ahh, looks like only the 'Custom amount' was affected? Nice rooting that out and thx for fix :)
